### ISSUE TITLE
save player name after a game ends

### ISSUE THREAD

**Issue by debanjan97** [debanjan97/EvoSnake#2]
- Modal should appear after a game ends, showing the score and asking for a name
- If there was a player before, have that player's username as default, player can change it if they want.
- There will be two CTA, one button for save and another for restart

**Comment by rohithZE** [comment]
Do they have to enter name everytime?

**Comment by debanjan97** [comment]
There will be the name of previous player in the text field. If player wants to change it, he or she can. To save the score, player should click on save
