### ISSUE TITLE
Pausing the game

### ISSUE THREAD

**Issue by debanjan97** [debanjan97/EvoSnake#3]
- Give user the ability to pause a game at any point of time
- During pause, a modal will be there with two buttons, one for "Resume" and one for "Restart"

**Comment by debanjan97** [comment]
- User should pause a game by clicking outside the board

**Comment by rohithreddy197** [comment]
Or we can have a pause button?

**Comment by debanjan97** [comment]
- Even we can have space too as a pause, we can have 3 ways to pause the game

**Comment by debanjan97** [comment]
Implemented
